spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:agendasenadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true          # imprime el SQL en consola
spring.jpa.properties.hibernate.format_sql=true


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always